services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: soberstreak
      POSTGRES_DB: soberstreak
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    container_name: soberstreak-migrate-dev
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile.migration
    environment:
      DATABASE_URL: postgresql://root:soberstreak@db:5432/soberstreak
    networks:
      - default
    profiles:
      - migration
    restart: 'no'

volumes:
  pgdata:
